name: Code Deployment
on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm install
          npm i -g @vercel/ncc semantic-release@beta @semantic-release/changelog @semantic-release/git @semantic-release/exec conventional-changelog-conventionalcommits
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
        run: |
          npx ncc build index.js
          npx semantic-release